home/urls.py
from django.urls import path
from .import views


app_name='home'
urlpatterns=[
		path('',views.index),
		path('register',views.register,name='register'),
		path('login',views.login,name='login'),
		path('home/<int:id>',views.home,name='home'),
		path('update/<int:id>',views.update,name='update'),
		path('changePassword/<int:id>',views.changePassword,name='changePassword'),
		path('logout',views.logout,name='logout'),
	]

testTemp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.
class SignUp(models.Model):
	Name = models.CharField(max_length=20,default='')
	Age=models.IntegerField(default='')
	Email=models.EmailField(default='')
	Password=models.CharField(max_length=12,default='')
	Photo=models.ImageField(upload_to='media/',default='')

home/forms.py
from django import forms
from . models import SignUp

class SignUpForm(forms.ModelForm):
	Password=forms.CharField(max_length=12,widget=forms.PasswordInput)
	ConformPassword=forms.CharField(max_length=12,widget=forms.PasswordInput)
	class Meta():
		model=SignUp
		fields='__all__'

class LoginForm(forms.ModelForm):
	Password=forms.CharField(max_length=12,widget=forms.PasswordInput)
	class Meta():
		model=SignUp
		fields=('Email','Password')

class UpdateForm(forms.ModelForm):
	class Meta():
		model=SignUp
		fields=('Name','Age','Email','Photo')

class ChangePasswordForm(forms.Form):
	OldPassword=forms.CharField(max_length=12,widget=forms.PasswordInput)
	Password=forms.CharField(max_length=12,widget=forms.PasswordInput)
	ConformPassword=forms.CharField(max_length=12,widget=forms.PasswordInput)
	

home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from . models import SignUp
from .forms import SignUpForm,LoginForm,UpdateForm,ChangePasswordForm
from django.contrib import messages
from django.contrib.auth import logout as logouts

# Create your views here.
def func1(request):
	return HttpResponse("Welcome to Django")

def index(request):
	
	return render(request,'index.html')

def register(request):
	if request.method=='POST':
		form1=SignUpForm(request.POST,request.FILES)
		if form1.is_valid():
			name=form1.cleaned_data['Name']
			age=form1.cleaned_data['Age']
			email=form1.cleaned_data['Email']
			password=form1.cleaned_data['Password']
			confirmPassword=form1.cleaned_data['ConformPassword']
			photo=form1.cleaned_data['Photo']
			user=SignUp.objects.filter(Email=email).exists()
			if user:
				messages.success(request,'Email Already Exist')
				return redirect('register/')
			elif password!=confirmPassword:
				messages.success(request,'Password missmatch')
				return redirect('register/')
			else:
				table=SignUp(Name=name,Age=age,Email=email,Password=password,Photo=photo)
				table.save()
				messages.success(request,'Registration Successful')
				return redirect('/')
	else:
		form1 =SignUpForm
	return render(request,'SignUp.html',{'form':form1})

def login(request):
	if request.method=='POST':
		form2=LoginForm(request.POST)
		if form2.is_valid():
			email=form2.cleaned_data['Email']
			password=form2.cleaned_data['Password']
			user=SignUp.objects.get(Email=email)
			if not user:
				messages.success(request,'Email does not exist')
				return redirect('login/')
			else:
				messages.success(request,'login successful')
				return redirect('/home/%s' % user.id)
	else:
		form2=LoginForm
	return render(request,'Login.html',{'form':form2})

def home(request,id):
	user=SignUp.objects.get(id=id)
	return render(request,'home.html',{'user':user})

def update(request,id):
	user=SignUp.objects.get(id=id)
	form=UpdateForm(request.POST or None,request.FILES or None,instance=user)
	if form.is_valid():
		form.save()
		messages.success(request,'Updated successfully')
		return redirect('/home/%s' % user.id)
	return render(request,'update.html',{'user':user,'form':form})

def changePassword(request,id):
	user=SignUp.objects.get(id=id)

	if request.method=='POST':
		form=ChangePasswordForm(request.POST)
		if form.is_valid():
			oldPassword=form.cleaned_data['OldPassword']
			password=form.cleaned_data['Password']
			confirmPassword=form.cleaned_data['ConformPassword']
			if oldPassword!=user.Password:
				messages.success(request,'Password does not exist')
				return redirect('/changePassword/%s' % user.id)
			elif password!=confirmPassword:
				messages.success(request,'Password missmatch')
				return redirect('changePassword/%s' % user.id)
			else:
				user.Password=password
				user.save()
				messages.success(request,'Password change successful')
				return redirect('/home/%s' % user.id)
	else:
		form=ChangePasswordForm()
	return render(request,'ChangePassword.html',{'user':user,'form':form})

def logout(request):
	logouts(request)
	messages.success(request,'logout successfully')
	return redirect('/')

home/templates/ChangePassword.html
{% extends 'base.html'%}
{% load static%}
{% block content %}
<body>
	{% for msg in messages %}



     <div class="alert alert-success alert-dismissible fade show" role="alert">
	  	 <strong>Hey!</strong>{{ msg }}
	  	 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	     	<span aria-hidden="true">&times;</span>
	     </button>
     </div>


    {% endfor %}
    <form action="{% url 'home:changePassword' user.id %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<table>
			<tr>
				<td>
					{{ form.as_table }}
				</td>
			</tr>
		</table>
		<input type="submit" value="Change" name="">
	</form>

</body>
</html>{% endblock %}

home/templates/Login.html
{% extends 'base.html'%}
{% load static%}
{% block content %}

<body>
	{% for msg in messages %}

	    <div class="alert alert-success alert-dismissible fade show" role="alert">
		  	 <strong>Hey!</strong>{{ msg }}
		  	 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		     	<span aria-hidden="true">&times;</span>
		     </button>
	    </div>
    {% endfor %}
	<div style="margin: 0 auto; border: 1px solid green; width:400px; height:100px;padding: 30px;">
	<form action="{% url 'home:login' %}" method="POST">
		{% csrf_token %}
		<table>
			<tr>
				<td>
					{{ form.as_table }}
				</td>
			</tr>
		</table>
		<input type="submit" value="Submit" name="">
	</form>
	</div>
</body>
{% endblock %}

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<title>Garden Truck</title>
<meta charset="utf-8">
<link rel="icon" href="{% static 'images/favicon.ico' %}">
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/slider.css' %}">
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery-migrate-1.1.1.js' %}"></script>
<script src="{% static 'js/superfish.js' %}"></script>
<script src="{% static 'js/sForm.js' %}"></script>
<script src="{% static 'js/jquery.equalheights.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/tms-0.4.1.js' %}"></script>
<script src="{% static 'js/jquery.carouFredSel-6.1.0-packed.js' %}"></script>
<script	src="{% static 'js/jquery.touchSwipe.min.js' %}"></script>
<script>
$(window).load(function () {
    $('.slider')._TMS({
        show: 0,
        pauseOnHover: false,
        prevBu: '.prev',
        nextBu: '.next',
        playBu: false,
        duration: 800,
        preset: 'fade',
        pagination: false, //'.pagination',true,'<ul></ul>'
        pagNums: false,
        slideshow: 8000,
        numStatus: false,
        banners: true,
        waitBannerAnimation: false,
        progressBar: false
    })
});
$(window).load(
    function () {
        $('.carousel1').carouFredSel({
            auto: false,
            prev: '.prev1',
            next: '.next1',
            width: 1030,
            items: {
                visible: {
                    min: 1,
                    max: 4
                },
                height: 'auto',
                width: 157,
            },
            responsive: true,
            scroll: 1,
            mousewheel: false,
            swipe: {
                onMouse: true,
                onTouch: true
            }
        });
    });
</script>
<!--[if lt IE 9]>
<script src="js/html5shiv.js"></script>
<link rel="stylesheet" media="screen" href="css/ie.css">
<![endif]-->
</head>
<body class="page1">
<header>
  <div class="container_12">
    <div class="grid_12">
      <div class="h_phone">Need Help? Call Us +1 (800) 123 4567</div>
      <h1><a href="index.html"><img src="{% static 'images/logo.png' %}" alt=""></a></h1>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
  </div>
  <div class="menu_block">
    <div class="container_12">
      <div class="grid_12">
        <div class="socials"><a href="#"></a><a href="#"></a></div>
        <div class="autor"> <a href="{% url 'home:login' %}">Login</a>
            <a href="{% url 'home:register' %}">Register</a> social </div>
        <nav class="">
          <ul class="sf-menu">
            <li class="current"><a href="index.html">Home</a></li>
            <li class="with_ul"><a href="about.html">About</a></li>
            <li><a href="services.html">Services</a>
              <ul>
                <li><a href="#"> Services List</a>
                  <ul>
                    <li><a href="#">Seeds</a></li>
                    <li><a href="#">Traits</a></li>
                    <li><a href="#">Safety Control</a></li>
                  </ul>
                </li>
                <li><a href="#">Overview</a></li>
                <li><a href="#">FAQS</a></li>
              </ul>
            </li>
            <li><a href="products.html">Products</a></li>
            <li><a href="blog.html">Blog</a></li>
            <li><a href="contacts.html">Contacts</a></li>
          </ul>
        </nav>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</header>
{% block content %}
{% endblock %}
<footer>
  <div class="container_12">
    <div class="grid_2">
      <div class="copy"> <a href="index.html" class="footer_logo"><img src="{% static 'images/footer_logo.png' %}"	alt=""></a> &copy; 2045 <a href="#">Privacy Policy</a> </div>
    </div>
    <div class="grid_2">
      <ul>
        <li><a href="#">Contact</a></li>
        <li><a href="#">Delivery</a></li>
        <li><a href="#">Legal Notice</a></li>
        <li><a href="#">Terms and Conditions</a></li>
        <li><a href="#">About Us</a></li>
      </ul>
    </div>
    <div class="grid_2">
      <ul>
        <li><a href="#">New Products</a></li>
        <li><a href="#">Top Sellers</a></li>
        <li><a href="#">Specials</a></li>
        <li><a href="#">Manufacturers</a></li>
        <li><a href="#">Suppliers</a></li>
      </ul>
    </div>
    <div class="grid_2">
      <ul>
        <li><a href="#">Science &amp; Safety</a></li>
        <li><a href="#">Product </a></li>
        <li><a href="#">Our Brands</a></li>
        <li><a href="#">Agricultural </a></li>
        <li><a href="#">Traits &amp; Technologies</a></li>
      </ul>
    </div>
    <div class="grid_3 prefix_1">
      <h4>Newsletter</h4>
      <form id="newsletter" action="#">
        <div class="success">Your subscribe request has been sent!</div>
        <label class="email"> <span>Enter e-mail address</span>
          <input type="email" value="" >
          <a href="#" class="btn" data-type="submit">Subscribe</a> <span class="error">*This is not a valid email address.</span> </label>
      </form>
    </div>
    <div class="clear"></div>
  </div>
  <div class="f_bot">
    <div class="container_12">
      <div class="grid_12">Design by: <a href="http://www.templatemonster.com/">TemplateMonster.com</a></div>
    </div>
  </div>
</footer>
</body>
</html>

home/templates/home.html
{% extends 'base.html'%}
{% load static%}
{% block content %}
<body>
	<h1>Welcome{{user.Name}}</h1>
	<table>
		<tr>
			<td>Age</td>
			<td>{{user.Age}}</td>
			<td><img src="{{user.Photo.url}}" height=300px width=300px></td>
		</tr>
		<tr><a href="{% url 'home:update' user.id %}">Update</a></tr>
		<tr><a href="{% url 'home:changePassword' user.id %}">Change Password</a></tr>
		<tr><a href="{% url 'home:logout' %}" >Logout</a></tr>
	</table>
</body>
{% endblock %}

home/templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="slider-relative">
	<div class="slider-block">
	  <div class="slider"> <a href="#" class="prev"></a> <a href="#" class="next"></a>
		<ul class="items">
		  <li> <img src="{% static 'images/slide.jpg' %}" alt="">
			<div class="banner">Healthy life <br>
			  <br>
			  tastes delicious</div>
		  </li>
		  <li> <img src="{% static 'images/slide1.jpg' %}" alt="">
			<div class="banner">A new generation <br>
			  <br>
			  of farming</div>
		  </li>
		  <li> <img src="{% static 'images/slide2.jpg' %}" alt="">
			<div class="banner">Best food is<br>
			  <br>
			  natural food</div>
		  </li>
		  <li> <img src="{% static 'images/slide3.jpg' %}" alt="">
			<div class="banner">New agricultural <br>
			  <br>
			  technologies only</div>
		  </li>
		</ul>
	  </div>
	</div>
  </div>
  <div class="content">
	<div class="black">
	  <div class="page1_block">
		<div class="container_12">
		  <div class="grid_12">
			<h2>Natural and fresh goods only!<br>
			  <br>
			  <br>
			  The best agricultural technologies</h2>
		  </div>
		  <div class="clear"></div>
		</div>
	  </div>
	  <div class="container_12">
		<div class="grid_3">
		  <h3>Harvest</h3>
		  <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
		  <a href="#" class="btn">More</a> </div>
		<div class="grid_3">
		  <h3>Cultivation</h3>
		  <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
		  <a href="#" class="btn">More</a> </div>
		<div class="grid_3">
		  <h3>Protection</h3>
		  <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
		  <a href="#" class="btn">More</a> </div>
		<div class="grid_3">
		  <h3>Treatment</h3>
		  <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
		  <a href="#" class="btn">More</a> </div>
		<div class="clear"></div>
	  </div>
	</div>
	<div class="white">
	  <div class="container_12">
		<div class="grid_7">
		  <h3>Company Products</h3>
		  <img src="{% static 'images/page1_img1.jpg' %}" alt="" class="img_inner fleft">
		  <div class="extra_wrapper">
			<div class="text1"> Aliquam placerat ligula eu sem facilj is semper porta sem pellentesque. </div>
			<p class="col1"><a class="col2" href="#">Click here</a> for more info about this free website template created by TemplateMonster.com </p>
			Lkhasellus id adipiscing nunc. Donecvelqq wr augue et nulla vehicula pretium. Donew ctryi weconsequat accumsan erat ac vu jo lputate. Kt consectetur commodo mollis. Ut necrci we tellus interdum aliquet. Johaseko kolo	lus id adipiscing nunc. Donec veldsak augue et nulr jver ehicula pretium. <br>
			<a href="#" class="btn">More</a> </div>
		</div>
		<div class="grid_4 prefix_1">
		  <h3>Technologies</h3>
		  <img src="{% static 'images/page1_img2.jpg' %}" alt="" class="img_inner fleft i1">
		  <div class="extra_wrapper">
			<div class="col1"> <a href="#">Mklhasellus aed hadipiscin nury.</a> </div>
			Konecvel whjugute etew nulla vehiculuote. pretium. Donew ctryi weconsequat accure msan erat ac vu jo lputatesectetur. </div>
		  <div class="clear cl1"></div>
		  <img src="{% static 'images/page1_img3.jpg' %}" alt="" class="img_inner fleft i1">
		  <div class="extra_wrapper">
			<div class="col1"> <a href="#">Uokhasellus id adipiscing nu.</a> </div>
			Honecvelqq whjugue et nulla vehiculuowe. Kjonecvelqq jugue et nulla vehiculoretium. Donew ctryi weconsequat accumsan. </div>
		  <div class="clear cl2"></div>
		  <img src="{% static 'images/page1_img4.jpg' %}" alt="" class="img_inner fleft i1">
		  <div class="extra_wrapper">
			<div class="col1 "> <a href="#">Lkokhasellusuop adipiscing nuretilo kolitri.</a> </div>
			Kjonecvelqq jugue et nulla vehiculoretium. Donew ctryi weconsequat accumsan erat ac vu jo lputateconsectetur commodo. </div>
		  <div class="clear"></div>
		  <a href="#" class="btn">More</a> </div>
		<div class="clear"></div>
	  </div>
	</div>
	<div class="gray">
	  <div class="container_12">
		<div class="grid_12">
		  <div class="car"> <a href="#" class="prev1"></a> <a href="#" class="next1"></a>
			<div class="car_div">
			  <ul class="carousel1">
				<li><a href="#"><img src="{% static 'images/logo1.png' %}" alt=""></a></li>
				<li><a href="#"><img src="{% static 'images/logo2.png' %}" alt=""></a></li>
				<li><a href="#"><img src="{% static 'images/logo3.png' %}" alt=""></a></li>
				<li><a href="#"><img src="{% static 'images/logo4.png' %}" alt=""></a></li>
				<li><a href="#"><img src="{% static 'images/logo2.png' %}" alt=""></a></li>
			  </ul>
			</div>
		  </div>
		</div>
		<div class="clear"></div>
	  </div>
	</div>
  </div>
{% endblock %}

home/templates/signUp.html
{% extends 'base.html'%}
{% load static%}
{% block content %}
<body>
	{% for msg in messages %}

     <div class="alert alert-success alert-dismissible fade show" role="alert">
	  	 <strong>Hey!</strong>{{ msg }}
	  	 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	     	<span aria-hidden="true">&times;</span>
	     </button>
     </div>


    {% endfor %}
	<form action="{% url 'home:register' %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<table>
			<tr>
				<td>
					{{ form.as_table }}
				</td>
			</tr>
		</table>
		<input type="submit" value="Submit" name="">
	</form>
</body>
{% endblock %}

home/templates/update.html
{% extends 'base.html'%}
{% load static%}
{% block content %}
<body>
	{% for msg in messages %}



     <div class="alert alert-success alert-dismissible fade show" role="alert">
	  	 <strong>Hey!</strong>{{ msg }}
	  	 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	     	<span aria-hidden="true">&times;</span>
	     </button>
     </div>


    {% endfor %}
	<form action="{% url 'home:update' user.id %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<table>
			<tr>
				<td>
					{{ form.as_table }}
				</td>
			</tr>
		</table>
		<input type="submit" value="Update" name="">
	</form>

</body>
{% endblock %}